2013-01-16 01:14:22.210060: ENGINE starting
2013-01-16 01:14:22.211485: ENGINE loading STUDENT ENGINE part 2
2013-01-16 01:14:22.220619: ENGINE loaded player module: OKComputer as player 1
2013-01-16 01:14:22.220934: QUORIDOR ENGINE CLIENT 1.0.5 by Adam Oest initializing
2013-01-16 01:14:22.391377: ENGINE calling STUDENT ENGINE init
2013-01-16 01:14:22.392444: STUDENT ENGINE init call successfully returned
2013-01-16 01:14:22.392659: ENGINE calling init() for player 1
2013-01-16 01:14:22.396154: OKComputer initialized as player 1
2013-01-16 01:14:22.404199: ENGINE GUI accessible at:
https://adelaide.cs.rit.edu/~royale/quoridorui/gameview/gameid.46232/partone.0/apikey.36bc8c65d1d4af66485/public.4493ae411d48d38cf128a62d5551b9ee0f3d451f50f64544658c6/animations.500/
2013-01-16 01:14:22.404827: ENGINE processing move # 1
2013-01-16 01:14:22.405083: ENGINE getting move for player 1 from PRE_MOVE list 
2013-01-16 01:14:22.405297: ENGINE validating player 1 move. Player 1 Wall: [0,2] -> [2,2]
2013-01-16 01:14:22.405418: ENGINE calling STUDENT ENGINE validate_move
2013-01-16 01:14:22.516495: STUDENT ENGINE validate_move call successfully returned
2013-01-16 01:14:22.534607: ENGINE uploading move to web engine
2013-01-16 01:14:22.773565: ENGINE detects correct move validation by STUDENT ENGINE
2013-01-16 01:14:22.785626: ENGINE calling STUDENT ENGINE last_move
2013-01-16 01:14:22.786111: STUDENT ENGINE last_move call successfully returned
2013-01-16 01:14:22.786289: ENGINE finished processing player 1's move
2013-01-16 01:14:22.822432: ENGINE notifying player 1 of last move
2013-01-16 01:14:22.824639: ENGINE finished with next move
2013-01-16 01:14:22.824900: ENGINE processing move # 2
2013-01-16 01:14:22.825027: ENGINE getting move for player 1 from PRE_MOVE list 
2013-01-16 01:14:22.825169: ENGINE validating player 1 move. Player 1 Wall: [0,2] -> [2,2]
2013-01-16 01:14:22.825269: ENGINE calling STUDENT ENGINE validate_move
2013-01-16 01:14:22.825466: ERROR: global name 'self' is not defined
2013-01-16 01:14:22.827017: TRACE: 
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Model\__init__.py", line 560, in studentEngineCall
  File "/home/wheeler/workspace/quoridor_group/StudentEngines/jak3122/__init__.py", line 342, in validate_move
    Logger.error(self,"Log: Invalid wall placement, overlaps valid wall.\n")
NameError: global name 'self' is not defined

2013-01-16 01:14:22.833658: ERROR: 2013-01-16 01:14:22.833590: ENGINE exiting due to STUDENT ENGINE exception

2013-01-16 01:14:22.856509: TRACE: 
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Engine\controller.py", line 246, in nextTurn
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Model\__init__.py", line 567, in studentEngineCall
Engine.security.GameException: 2013-01-16 01:14:22.833590: ENGINE exiting due to STUDENT ENGINE exception


2013-01-16 01:14:23.075075: 2013-01-16 01:14:22.833590: ENGINE exiting due to STUDENT ENGINE exception

2013-01-16 01:14:23.107044: ENGINE finished with next move
2013-01-16 01:14:23.127122: ENGINE shutting down
