2013-01-22 23:19:55.654460: ENGINE starting
2013-01-22 23:19:55.658692: ENGINE loading STUDENT ENGINE part 3
2013-01-22 23:19:55.693399: ENGINE loaded player module: OKComputer as player 1
2013-01-22 23:19:55.694636: ENGINE loaded player module: Human as player 2
2013-01-22 23:19:55.694841: QUORIDOR ENGINE CLIENT 1.0.5 by Adam Oest initializing
2013-01-22 23:19:57.183707: ENGINE calling STUDENT ENGINE init
2013-01-22 23:19:57.184964: STUDENT ENGINE init call successfully returned
2013-01-22 23:19:57.185116: ENGINE calling init() for player 1
2013-01-22 23:19:57.185166: ENGINE calling STUDENT ENGINE initialize_player
2013-01-22 23:19:57.185896: OKComputer initialized as player 1
2013-01-22 23:19:57.186052: STUDENT ENGINE initialize_player call successfully returned
2013-01-22 23:19:57.186176: ENGINE calling init() for player 2
2013-01-22 23:19:57.186288: ENGINE calling STUDENT ENGINE initialize_player
2013-01-22 23:19:57.186463: STUDENT ENGINE initialize_player call successfully returned
2013-01-22 23:19:57.194126: ENGINE GUI accessible at:
https://adelaide.cs.rit.edu/~royale/quoridorui/gameview/gameid.69241/partone.0/apikey.36bc8c65d1d4af66485/public.0be4e99fd9fa3d0468a719e2a54192bc4f8395db50ff64ed0d391/animations.500/
2013-01-22 23:19:57.199657: ENGINE calling STUDENT ENGINE next_move
2013-01-22 23:19:57.201581: ERROR: last_move() takes exactly 2 arguments (1 given)
2013-01-22 23:19:57.211977: TRACE: 
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Model\__init__.py", line 560, in studentEngineCall
  File "/home/wheeler/workspace/quoridor_group/StudentEngines/jak3122/__init__.py", line 509, in next_move
    engineData=last_move(engineData)
TypeError: last_move() takes exactly 2 arguments (1 given)

